### ISSUE TITLE
Profile: editing "School" and "Location", saving problem

### ISSUE THREAD

**Issue by yejipark** [WeStudee/WeStudee#18]
Using Google Chrome on my laptop (Windows 8).

![image](https://cloud.githubusercontent.com/assets/11168182/6424238/d30ad102-bec2-11e4-9305-26d96ad3f3ad.png)

I can register my name, major, and preferred email but not school and location.
Also, if I click "EDIT" next to "Courses", it goes back to blank page (below screenshot) and my profile is not saved.

![image](https://cloud.githubusercontent.com/assets/11168182/6424246/1e50f01a-bec3-11e4-921e-0ddd6a326529.png)

**Comment by yutarochan** [comment]
This is an intentional feature: Since this is a subscription based service, users will be registering using their school email address, which will automatically fill in those parameters and locking them upon registration. 

Example: If you try an email like xxxxx@student.goodwin.edu, then the profile will be prefilled with Goodwin College for school and East Hartford, CT for Location (probably will have to make location flexible due to the possibility of multiple campus locations under the same school name.)

[EDIT]: This needs verification.
