### ISSUE TITLE
Course List - Not Showing

### ISSUE THREAD

**Issue by jwhipple26** [WeStudee/WeStudee#25]
I created a profile in Chrome and Safari on Mac OS successfully and was had an issue with selecting courses.  The page was blank, so it was not possible to add/select courses.

![screenshot 2015-03-11 14 13 33](https://cloud.githubusercontent.com/assets/10063859/6603506/03c1f322-c7f9-11e4-813b-4c42c2e5b521.png)

**Comment by yejipark** [comment]
I tested Chrome and IE. Like Joel, the course list was not shown in Chrome.
In IE, courses were shown, but I saw some subject titles are misspelled (Englsih) or incongruous (HIST and history). But I didn't report this as an additional issue because I assumed this is the problem with the course list Goodwin offered us, not functionality/bug of our site, and can be easily corrected.

**Comment by yutarochan** [comment]
As I've mentioned in the Slack, this issue is caused due to the email restriction that has been set by the system. As per spec, we have specified that signups can only be permitted through school email addresses and since you are using a gmail.com or yahoo.com, the system will not pick up the email for the corresponding school during the signup process. We will have to test using real email addresses to ensure that the logic will remain the same during production testing.
